apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-app
  name: mysql
  namespace: default
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-app
  clusterIP: None
