apiVersion: v1
kind: PersistentVolume
metadata:
    labels:
     type: local
    name: mysql-pv
spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 250Mi
    hostPath:
      path: /mnt/data
    persistentVolumeReclaimPolicy: Retain
    storageClassName: standard
    volumeMode: Filesystem
