apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
      app: mysql-app
    name: mysql-pv-claim
    namespace: default
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 250Mi
    storageClassName: standard
    volumeMode: Filesystem
